site_name: nixianjun6
nav:
-Home: index.md
-Database: database.md
theme:
  name: 'dracula'
  logo: https://github.com/nixianjun6/blog/tree/master/site/images/nixianjun6.png
  favicon: https://github.com/nixianjun6/blog/tree/master/site/images/favicon.ico